# Generated by Django 4.2.27 on 2026-02-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_need_sn_alter_stockitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出库时间'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='售出价格'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单总金额'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实收/实付金额'),
        ),
    ]
