# Generated by Django 4.2.27 on 2026-02-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stockitem_out_time_stockitem_sold_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='out_time',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='sold_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='状态(审核)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额'),
        ),
    ]
