# Generated by ChatGPT patch: make migration idempotent for existing columns
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_stockitem_out_time_stockitem_sold_price_and_more'),
    ]

    operations = [
        # DB-level: add columns if not exists (PostgreSQL)
        migrations.RunSQL(
            sql=[
                "ALTER TABLE core_transaction ADD COLUMN IF NOT EXISTS is_voided boolean NOT NULL DEFAULT false;",
                "ALTER TABLE core_transaction ADD COLUMN IF NOT EXISTS void_reason varchar(255) NULL;",
                "ALTER TABLE core_transaction ADD COLUMN IF NOT EXISTS voided_at timestamp with time zone NULL;",
                "ALTER TABLE core_transaction ADD COLUMN IF NOT EXISTS corrected_from_id bigint NULL;",
                "ALTER TABLE core_transaction ADD COLUMN IF NOT EXISTS corrected_to_id bigint NULL;",
                # add FK constraints if not exists (use DO blocks)
                """DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'core_transaction_corrected_from_id_fkey'
    ) THEN
        ALTER TABLE core_transaction
        ADD CONSTRAINT core_transaction_corrected_from_id_fkey
        FOREIGN KEY (corrected_from_id) REFERENCES core_transaction(id)
        DEFERRABLE INITIALLY DEFERRED;
    END IF;
END$$;""",
                """DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'core_transaction_corrected_to_id_fkey'
    ) THEN
        ALTER TABLE core_transaction
        ADD CONSTRAINT core_transaction_corrected_to_id_fkey
        FOREIGN KEY (corrected_to_id) REFERENCES core_transaction(id)
        DEFERRABLE INITIALLY DEFERRED;
    END IF;
END$$;""",
                "CREATE INDEX IF NOT EXISTS core_transaction_is_voided_idx ON core_transaction(is_voided);",
            ],
            reverse_sql=[
                # Keep reverse minimal/safe; don't drop if other migrations rely on it
                "DROP INDEX IF EXISTS core_transaction_is_voided_idx;",
                # Drop constraints then columns
                """DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'core_transaction_corrected_from_id_fkey') THEN
        ALTER TABLE core_transaction DROP CONSTRAINT core_transaction_corrected_from_id_fkey;
    END IF;
END$$;""",
                """DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'core_transaction_corrected_to_id_fkey') THEN
        ALTER TABLE core_transaction DROP CONSTRAINT core_transaction_corrected_to_id_fkey;
    END IF;
END$$;""",
                "ALTER TABLE core_transaction DROP COLUMN IF EXISTS corrected_to_id;",
                "ALTER TABLE core_transaction DROP COLUMN IF EXISTS corrected_from_id;",
                "ALTER TABLE core_transaction DROP COLUMN IF EXISTS voided_at;",
                "ALTER TABLE core_transaction DROP COLUMN IF EXISTS void_reason;",
                "ALTER TABLE core_transaction DROP COLUMN IF EXISTS is_voided;",
            ],
            # Ensure Django state knows about fields without re-adding columns.
            state_operations=[
                migrations.AddField(
                    model_name='transaction',
                    name='is_voided',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='void_reason',
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='voided_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='corrected_from',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='core.transaction'),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='corrected_to',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originals', to='core.transaction'),
                ),
            ],
        ),
    ]
